# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 4
suits = ["♣️", "♦️", "❤️", "♠️"]
ranks = [None, "A"] + [str(n) for n in range(2, 11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb 14
class Card:
    """Class representing a card"""

    def __init__(
        self, suit: int, rank: int  # Index of the `suits`  # Index of the `ranks`
    ):
        self.suit, self.rank = suit, rank

    def __str__(self):
        # return f"Card({self.suit}->{suits[self.suit]}, {self.rank}->{ranks[self.rank]})"
        s = suits[self.suit]
        r = ranks[self.rank]
        c = f"""
            __________
            |{s}       |
            |        |
            |        |
            |       {r}|
            ----------
        """
        return c

    __repr__ = __str__

    def __lt__(self, c: "Card"):  # Another card to compare with
        return (self.suit, self.rank) < (c.suit, c.rank)

    def __gt__(self, c: "Card"):  # Another card to compare with
        return (self.suit, self.rank) > (c.suit, c.rank)
